### ISSUE TITLE
ISDA SIMM 2.5

### ISSUE THREAD

**Issue by suhasghorp** [meenmo/ISDA_SIMM#2]
Hello,

Thank you for making your SIMM python codes available on GitHub. Are you planning to update for version 2.5 that was released recently? Also, have you tried running the ISDA SIMM Unit tests on your model ? 
Thanks again.

**Comment by meenmo** [comment]
Let me update v2.5 soon! Or you can make a pull request for src/weights_corr2_5.py if you wish :) But I don't have an access to the unit test for v2.5.

**Comment by suhasghorp** [comment]
I will try to create a pull request but not sure when I will get to it. The tests you have for version 2.4 - are those ISDA tests or your own ? I am pretty sure ISDA used to publish the unit tests but I can't seem to find their tests online anymore.

**Comment by meenmo** [comment]
Hello, 

I have no access to the test either, but am pretty sure there will be other way to validate. And I just updated v2.5 params!

Please take a look and let us know if there's anything to correct or improve :)
