### ISSUE TITLE
Unit Tests Not validated

### ISSUE THREAD

**Issue by LeoMessiiiii** [meenmo/ISDA_SIMM#3]
Hi ,

Thank you so much , I tried to validate the ISDA Unit Test (Its free) and I have find some test that doesn't pass the test using your code. 

Exemple when crif file is : 

portfolio_id,trade_id,collect_regulations,product_class,risk_type,qualifier,bucket,label1,label2,amount,amount_currency,amountusd
C330,C330.S_IRV_16,All,RatesFX,Risk_InflationVol,USD,,30y,,80000000.0,USD,80000000.0
C330,C330.S_IRV_21,All,RatesFX,Risk_InflationVol,USD,,2w,,-80000000.0,USD,-80000000.0

Official unit test expect the result to be 0 and your code return a Curvature of 2,442,463.46

An other failed test :

portfolio_id,trade_id,collect_regulations,product_class,risk_type,qualifier,bucket,label1,label2,amount,amount_currency,amountusd
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0

Official unit test expect the result to be 1,898,530,683.542 and your return a Vega          1,706,855,277.77

If you have an idea to correct it and validate all unit test it will be really good. Thank you for all.

**Comment by meenmo** [comment]
Thanks for your response!

Could you advise which version did you try?

**Comment by LeoMessiiiii** [comment]
Yes , it was the last version 2.5 . Just for information only some tests have failed , most of them are validated.

**Comment by meenmo** [comment]
I have no access to the unit test v2.5. I would appreciate if you could upload the regarding crif in csv through a pull request or any other way around; so that I can look them up!

**Comment by LeoMessiiiii** [comment]
I have put 2 examples of crif file , you can create a file csv and copy past this on the file for the first failed test for example ;
portfolio_id,trade_id,collect_regulations,product_class,risk_type,qualifier,bucket,label1,label2,amount,amount_currency,amountusd
C330,C330.S_IRV_16,All,RatesFX,Risk_InflationVol,USD,,30y,,80000000.0,USD,80000000.0
C330,C330.S_IRV_21,All,RatesFX,Risk_InflationVol,USD,,2w,,-80000000.0,USD,-80000000.0

Maybe you need to change to columns names. Expected output is 0 .

And the other one is the same a file csv and you past this :

portfolio_id,trade_id,collect_regulations,product_class,risk_type,qualifier,bucket,label1,label2,amount,amount_currency,amountusd
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0
C349,C349.S_FXV_7,All,RatesFX,Risk_FXVol,RUBTRY,,5y,,-12000000.0,USD,-12000000.0

Official unit test expect the result to be 1,898,530,683.542 and your return a Vega 1,706,855,277.77

**Comment by meenmo** [comment]
I am looking into the case for Risk_InflationVol.

As for the case Risk_FXVol, 1,898,530,683.542 is returned as you said when RW(risk weight) is 14.6, which is the case both given currency and calculation currency are considered to be high volatility group according to the clause 69(p.24). However, as long as the calculation currency is USD, RW cannot be 14.6. 

I don't think the numbers in the unit tests are incorrect, but I would appreciate if you could share any idea on this matter. I will update here as soon as I find something!

**Comment by LeoMessiiiii** [comment]
Happy new year , just for information , for the FXVol unit test the RW is 14.6 . As you can see in 10 (b) (p.5) : 

For FX vega (which depends on a pair of currencies), the risk weight to use here is the entry from the FX delta risk weight table, given in section I, whose row is the FX volatility group of the first currency and whose column is the FX volatility group of the second currency.

In our case RUBTRY then RW = 14.6 .

**Comment by OpenInsightsNow** [comment]
@LeoMessiiiii Where can I find the ISDA Unit Tests? Perhaps I can implement them and make a pull request on this repo.

**Comment by LeoMessiiiii** [comment]
Hello,

You can use this one (Combinations (10-day))

[ISDA-SIMM-UnitTesting-v2.5.xlsx](https://github.com/meenmo/ISDA_SIMM/files/12208887/ISDA-SIMM-UnitTesting-v2.5.xlsx)

**Comment by OpenInsightsNow** [comment]
@LeoMessiiiii Thank you for the extremely fast response!

**Comment by meenmo** [comment]
@LeoMessiiiii Oh thank you so much! Let me take a look and fix any bugs soon!

**Comment by meenmo** [comment]
@LeoMessiiiii Thanks for your sharing!! Let me take a look too!
@OpenInsightsNow Always welcome your contribution!!

**Comment by LeoMessiiiii** [comment]
It's been a very long time since I forgot that I had fixed the unit tests to make them pass, but I don't remember if all the tests were passing or not. 

There have been some changes :

1. Be sure to use weights_corr2_5

2. On agg_sensitivites.py => In my case the Base Ccy is 'EUR' then i change : 

`calculation_currency = 'USD'`
 By
`calculation_currency = Simm_calculation_currency`

--> add an exchange rate on margin_risk_class.py => for example :
`
T = wnc.T(risk_class,'Delta',bucket=bucket)
VT  = wnc.T('Rates','Vega',currency=currency)
`
By:
` 
T = wnc.T(risk_class,'Delta',bucket=bucket) * self.exchange_rate
VT  = wnc.T('Rates','Vega',currency=currency) * self.exchange_rate
`

`
is_given_currency = (currency_pair[:3] in wnc.high_vol_currency_group or currency_pair[3:] in wnc.high_vol_currency_group) 
is_calc_currency  = self.calculation_currency in wnc.high_vol_currency_group
`
By

`
is_given_currency = (currency_pair[0:3] in wnc.high_vol_currency_group)
is_calc_currency = (currency_pair[3:6] in wnc.high_vol_currency_group)
`

I also change : 

`updates['Rates']['Curvature'] += max(CVR_sum + _lambda * sqrt(K), 0) / (HVR**2)`
By
`
                if risk_class == 'Risk_InflationVol' and S < 0:
                    updates['Rates']['Curvature'] = 0
                else:
                    updates['Rates']['Curvature'] += max(CVR_sum + _lambda * sqrt(K), 0) / (HVR**2)
`


4. To Avoid some crashes :


Replace 
`crif_risk_class = self.crif[(self.crif['risk_type']==risk_class) & (str(self.crif['bucket']).lower() =='residual')]`

By : `crif_risk_class = self.crif[(self.crif['risk_type']==risk_class) & (self.crif['bucket'].str.lower().isin(['residual']))]`

In Utils.py : 

`if 'residual' in (str.lower() for str in list(df['bucket'])) `
By
`if 'residual' in (str(y).lower() for y in list(df['bucket']))`

In Agg_margins.py , i have added onlyaddon = false and changed :
df_total_err['SIMM Total'] = df_total['SIMM Total'] = simm_total
By:
        if (df_total.empty or df_total_err.empty) and addon_margin != 0:
            dt = {'SIMM Total' : [simm_total] ,'Add-On' : [addon_margin]}
            df = pd.DataFrame(dt)
            onlyAddon = True
            return df, error_occured, onlyAddon
        else:
            df_total_err['SIMM Total'] = df_total['SIMM Total'] = simm_total

**Comment by OpenInsightsNow** [comment]
In my preliminary investigation, I found that 43 of the 497 unit tests fail.  I have not checked that the test results from the spreadsheet are correct. As per LeoMessii's comment on Jan 2, I think there might be a bug on in 'margin_risk_class' on line 446. The calc currency and given currency seem to be switched incorrectly. This error may be repeated two other times in the code base.  I will make a pull request when I get the time.

['C330', 'C342', 'C349', 'C359', 'C391', 'C392', 'C393', 'C397', 'C401', 'C415',
 'C416', 'C418', 'C419', 'C420', 'C426', 'C449', 'C451', 'C452', 'C453', 'C454',
 'C456', 'C457', 'C458', 'C459', 'C466', 'C471', 'C472', 'C478', 'C479', 'C480',
 'C481', 'J1', 'J2', 'J3', 'J4', 'J5', 'J6', 'J7', 'J8', 'J9',
 'J10', 'JS1', 'JS2']

**Comment by OpenInsightsNow** [comment]
@LeoMessiiiii Test C349 from the unit test is now passing based upon fix in my pull request.

**Comment by LeoMessiiiii** [comment]
Its been a long time as i said before , in my side I did the same correction to pass this test :)

**Comment by OpenInsightsNow** [comment]
@LeoMessiiiii: How did you determine this fix?  I know you said it was a long time ago, but perhaps you still have some idea.

if risk_class == 'Risk_InflationVol' and S < 0: 
       updates['Rates']['Curvature'] = 0 
else: 
        updates['Rates']['Curvature'] += max(CVR_sum + _lambda * sqrt(K), 0) / (HVR**2)

**Comment by meenmo** [comment]
In C.1) 14 (p9), there states that "All sensitivities to inflation rates for the same currency are fully offset". So the following C330 can be 0:
C330,C330.S_IRV_16,All,RatesFX,Risk_InflationVol,USD,,30y,,80000000.0,USD,80000000.0
C330,C330.S_IRV_21,All,RatesFX,Risk_InflationVol,USD,,2w,,-80000000.0,USD,-80000000.0

However, I don't understand why C331 is not 0 then:
C331      RatesFX       S_IRV_19                All  Risk_InflationVol       CAD    NaN    10y    NaN   10000000            USD   10000000
C331      RatesFX       S_IRV_22               All  Risk_InflationVol       CAD    NaN    30y    NaN  -10000000            USD  -10000000

**Comment by LeoMessiiiii** [comment]
@OpenInsightsNow in our side we don't have 'Risk_InflationVol' in our Crif i think i did this just to pass some unit test...(i know its not clean :) )

@meenmo here the IRvega/curvature is calculated for CAD and for the unit test the currency is USD

**Comment by meenmo** [comment]
@LeoMessiiiii Thanks for your reply! 

I am working onward and got stuck at C335 though. Appreciate if anyone could share any idea on C335!

**Comment by LeoMessiiiii** [comment]
No pb in my side maybe you can find solution in this comment https://github.com/meenmo/ISDA_SIMM/issues/3#issuecomment-1657889729

**Comment by jmcason** [comment]
@meenmo I cannot remember whether test C335 was passing for me. I will check and respond. Also, I will push my (very basic) unit tests.

**Comment by OpenInsightsNow** [comment]
Test C335 works fine for me.  It is strange that the test is failing for you.

**Comment by meenmo** [comment]
Hi all,

I've updated v2.6 with minor fix. Please open issue if needed.

Thanks for your contribution!

**Comment by suhasghorp** [comment]
@LeoMessiiiii @OpenInsightsNow 

Any chance you might have ISDA SIMM Unit Testing spreadsheets for 2.6 and 2.7 versions of the model ? I am working on generating Test cases for each Combination id that can be auto-run in python and it would help a lot if we could make sure the model passes 2.6 and 2.7 tests. Thank you!
